### ISSUE TITLE
בכפתורים של הזמנה מהצד של הלקוח לשנות ולעשות שיראו כמו כפתורים

### ISSUE THREAD

**Issue by Jestriker** [tgilabs/workway-bugs#16]
### מה הרעיון שלכם?

כאשר לקוח מעוניין לסיים הזמנה הוא לוחץ על ״אישור וסגירת הזמנה ( אין דרך חזרה ⚠️ )״, בנוסף יש עוד שני כפתורים של ״דחה/בקשה לתיקונים״ וגם ״תלונה״, כל אלו לא הראים כמו כפתורים ובבקשה לשנות אותם לצבע הסגול של הפלטפורמה שיוכלו להבדיל שזה כפתורים כי כרגע זה נראה כמו טקסט ולא כמו משהו שאפשר ללחוץ עליו, זה כולל את שלושת הכפתורים.

### לאיזה מערכת תרצו להוסיף את הפונקציונליות?

מערכת הפוסטים הראשית

**Comment by thefourcraft** [comment]
העדכון באוויר
