### ISSUE TITLE
לא מעלה לי קובץ לגלרייה

### ISSUE THREAD

**Issue by ArielosYosef** [tgilabs/workway-bugs#17]
### מה קרה?

 כשאני מנסה להעלות קובץ לגלרייה זה טוען כבר יותר משעה ואני לא חושב שזה הולך להסתיים מתישהו. גודל הקובץ הוא 150 מגה בייט או זה עוזר

### היכן קרה הבעיה?

עריכת המודעה

### באיזה דפדפן מתרחשת הבעיה?
google chrome

### סוג המכשיר
pc

**Comment by thefourcraft** [comment]
כן המערכת לא מאפשרת להעלות קבצים מעל 40 mb בסרטונים כרגע
היא צריכה גם להציג הודעת שגיאה, אז כנראה שיש פה באג :)
תודה על הדיווח, ככה אתם עוזרים לנו לשפר את הפלטפורמה

**Comment by ArielosYosef** [comment]
אוקיי תודה על המידע. פעם הבאה
 אדאג לספק קבצים יותר קטנים.
