### ISSUE TITLE
[בעייה]: יש לופ של כניסה

### ISSUE THREAD

**Issue by NoomShoor** [tgilabs/workway-bugs#18]
### מה קרה?

אני מנסה להתחבר למשתמש שלי וכשאני לוחץ על התחברות עם גוגל ואני מתחבר זה מנתק אותי ועושה לי את זה שוב ושוב ושוב
בקיצור קורה לופ או שקורה עוד משהו בסרטון שצירפתי 

https://github.com/tgilabs/workway-bugs/assets/168352126/0022b554-8871-4158-b370-da0221d4dcf7

### היכן קרה הבעיה?

התחברות למערכת

### באיזה דפדפן מתרחשת הבעיה?

Chrome

### סוג המכשיר

PC (Windows)

**Comment by thefourcraft** [comment]
בעיית ההתחברות למערכת הצ׳אט כאשר משתמש אינו מחובר סודרה, עכשיו תועברו למסך הכניסה הרגיל של הפלטפורמה ולא מסך הכניסה של צוות המעבדה
תודה על הדיווח! ככה אתם עוזרים לנו לשפר את הפלטפורמה
