### ISSUE TITLE
יציאה אוטומטית מהאתר

### ISSUE THREAD

**Issue by stivendarsi** [tgilabs/workway-bugs#19]
### מה קרה?

בדומה ל #18 , כשאני נכנס עם הדיסקורד לאתר ואז יוצא מהאתר ופותח שוב, אני צריך להתחבר מחדש.

### היכן קרה הבעיה?

התחברות למערכת

### באיזה דפדפן מתרחשת הבעיה?

Chrome

### סוג המכשיר

PC (Windows)

**Comment by thefourcraft** [comment]
הבעייה #18 היא על מערכת הצ'אט,
אנחנו נבדוק את העניין אם היציאה מהפלטפורמה
