### ISSUE TITLE
[בעייה]: לא ניתן להתחבר דרך הדיסקורד דרך הדפדפן Arc

### ISSUE THREAD

**Issue by hayhany** [tgilabs/workway-bugs#2]
### מה קרה?

לא ניתן להתחבר לאתר דרך דיסקורד דרך הדפדפן Arc בווינדוס 11
התחברות מתאפשרת מדפדפנים אחרים, יכול להיות שהבעיה היא בדפדפנים מבוססים Chromium

כאשר מנסים להתחבר זה מחזיר לאותו עמוד רק שעדיין לא מחובר לחשבון

### היכן קרה הבעיה?

התחברות למערכת

### באיזה דפדפן מתרחשת הבעיה?

Arc

### סוג המכשיר

PC (Windows)

**Comment by thefourcraft** [comment]
יכול להיות כי זה בעייה מקומית אצלך, אבל בכל אופן לפעמים יש התנגדות של מטמון
https://workway.co.il/docs/solving-problems-logging-into-the-platform/
