### ISSUE TITLE
[בעיה]: אפשרות לשים איזה מספר טלפון שבא לך בלי בדיקה שאתה הבעלים שלו

### ISSUE THREAD

**Issue by SimplyRan** [tgilabs/workway-bugs#26]
### מה קרה?

אתה יכול לשים איזה מספר טלפון שבא לך כגון  050000000
וזה לא יבדוק מי הבעלים של אותו המספר .

### היכן קרה הבעיה?

פרופיל אישי

**Comment by thefourcraft** [comment]
אין צורך לבדוק, מוכר שלא יכניס מספר טלפון אמיתי ולא נוכל ליצור קשר איתו זה בעייה שלו
