### ISSUE TITLE
תמונות לא מתעדכנות

### ISSUE THREAD

**Issue by DrifeDev** [tgilabs/workway-bugs#4]
### מה קרה?

ברגע שמעדכנים תמונה, התמונה לא מתעדכנת אלא אם לוחצים עליה.

זה קורה גם בתוך הכרטיסיות כשמחפשים מודעות, וגם בתמונות של המודעה.
התמונה המעודכנת מופיעה כשלוחצים על התמונה להגדלה.

הוספתי סרטון בו אפשר לראות שהתמונה בכרטיסייה, לא תואמת למודעה כשנכנסים למודעה וגם היא לא תואמת למודעה שמופיעה כשלוחצים על התמונה.

https://github.com/tgilabs/workway-bugs/assets/162193336/c670a8a7-e09c-45cf-9c28-bfd9a27e0f5f

מזכיר שיש עוד באג שקשור לתמונות: https://github.com/tgilabs/workway-bugs/issues/1

### היכן קרה הבעיה?

מערכת הפוסטים הראשית

### באיזה דפדפן מתרחשת הבעיה?

Arc

### סוג המכשיר

PC (Windows)

**Comment by thefourcraft** [comment]
https://github.com/tgilabs/workway-bugs/issues/1
נראה שזה קשור לאותה הבעייה, זה יסודר במהלך השבוע הזה או שבוע הבא 🤞
