### ISSUE TITLE
[הצעה לשיפור]: שינוי צבע הכפתור "הזמנה אישית" לצבע שיותר מושך את העין.

### ISSUE THREAD

**Issue by JustMe-png** [tgilabs/workway-bugs#7]
### מה הרעיון שלכם?

אני רוצה לראות את הפונקציונליות הזו במערכת כי כרגע לא שמים לב לכפתור - מה הצבע? 
#A04EEA

### לאיזה מערכת תרצו להוסיף את הפונקציונליות?

מערכת הזמנת פרוייקט אישי

**Comment by thefourcraft** [comment]
טופל ועלה לפלטפורמה
