### ISSUE TITLE
הקרוסלה דפוקה

### ISSUE THREAD

**Issue by TEGRIA1** [tgilabs/workway-bugs#8]
### מה קרה?

נכנסתי לאתר והייתי בדף בית הבחנתי בקרוסלה שלא מונעת, זאת אומרת לא זזה כלל... 
הייתי שמח לדווח על בעיה זאת , בנוסף לבעיה זאת. הקרוסלה מציגה תמונה "בלתי נראת" לעין . 
ולמטה הנקודות לא באמצה.

### היכן קרה הבעיה?

לינק שבור

**Comment by thefourcraft** [comment]
סודר
