### ISSUE TITLE
הוספת קישור מדף "שאלות ותשובות" מתחת לכל השאלות שמעביר לעמוד ה Support

### ISSUE THREAD

**Issue by JustMe-png** [tgilabs/workway-bugs#9]
### מה הרעיון שלכם?

לרשום "במידה ולא מצאתם את התשובה שאתם מחפשים, מביך... אבל תרגישו חופשי לפנות ל**צוות התמיכה** שלנו!"
(המילה צוות התמיכה היא a link שיוביל ל-
workway.co.il/support
)
וזהו בתכלס זה חשוב מאוד!

### לאיזה מערכת תרצו להוסיף את הפונקציונליות?

מדריך למשתמש

**Comment by thefourcraft** [comment]
Added 
![image](https://github.com/tgilabs/workway-bugs/assets/90725541/07206336-3f5e-440b-ab91-ca3fe97812cc)
